root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - playgroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - publicTransportDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sportsGroundDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - trainDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - sweetshopDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - convenienceStoreDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pubDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - theaterDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - veterinaryDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - restaurantDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - schoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - postOfficeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - pharmacyDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - atmDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - doctorDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - preSchoolDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
UnboundLocalError: local variable 'dict_poi' referenced before assignment
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - cinemaDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kino'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Obchod'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
root - WARNING - s_usableArea was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 159, in extractData
    s_usableArea = dict_detailsTableOfOffer['Užitná plocha']
KeyError: 'Užitná plocha'
root - WARNING - s_terraceSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 165, in extractData
    s_terraceSqMeter = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellarSqMeter was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 171, in extractData
    s_cellarSqMeter = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_priceNote was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 177, in extractData
    s_priceNote = dict_detailsTableOfOffer['Poznámka k cenì']
KeyError: 'Poznámka k cenì'
root - WARNING - s_location was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 183, in extractData
    s_location = dict_detailsTableOfOffer['Umístìní objektu']
KeyError: 'Umístìní objektu'
root - WARNING - s_floor was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 189, in extractData
    s_floor = dict_detailsTableOfOffer['Podlaží']
KeyError: 'Podlaží'
root - WARNING - s_building was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 195, in extractData
    s_building = dict_detailsTableOfOffer['Stavba']
KeyError: 'Stavba'
root - WARNING - s_buildingCondition was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 201, in extractData
    s_buildingCondition = dict_detailsTableOfOffer['Stav objektu']
KeyError: 'Stav objektu'
root - WARNING - s_lift was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 207, in extractData
    s_lift = dict_detailsTableOfOffer['Výtah']
KeyError: 'Výtah'
root - WARNING - s_ownership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 213, in extractData
    s_ownership = dict_detailsTableOfOffer['Vlastnictví']
KeyError: 'Vlastnictví'
root - WARNING - s_id was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 219, in extractData
    s_id = dict_detailsTableOfOffer['ID zakázky']
KeyError: 'ID zakázky'
root - WARNING - s_idOrder was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 225, in extractData
    s_idOrder = dict_detailsTableOfOffer['ID']
KeyError: 'ID'
root - WARNING - s_energyPerformanceOfBuilding was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 231, in extractData
    s_energyPerformanceOfBuilding = dict_detailsTableOfOffer['Energetická nároènost budovy']
KeyError: 'Energetická nároènost budovy'
root - WARNING - s_water was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 237, in extractData
    s_water = dict_detailsTableOfOffer['Voda']["value"]
KeyError: 'Voda'
root - WARNING - s_gas was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 243, in extractData
    s_gas = dict_detailsTableOfOffer['Plyn']["value"]
KeyError: 'Plyn'
root - WARNING - s_heating was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 249, in extractData
    s_heating = dict_detailsTableOfOffer['Topení']["value"]
KeyError: 'Topení'
root - WARNING - s_waste was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 255, in extractData
    s_waste = dict_detailsTableOfOffer['Odpad']["value"]
KeyError: 'Odpad'
root - WARNING - s_electricity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 261, in extractData
    s_electricity = dict_detailsTableOfOffer['Elektøina']["value"]
KeyError: 'Elektøina'
root - WARNING - s_connectivity was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 267, in extractData
    s_connectivity = dict_detailsTableOfOffer['Telekomunikace']
KeyError: 'Telekomunikace'
root - WARNING - s_transport was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 273, in extractData
    s_transport = getStringFromList(dict_detailsTableOfOffer, "Doprava")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Doprava'
root - WARNING - s_roads was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 279, in extractData
    s_roads = getStringFromList(dict_detailsTableOfOffer, "Komunikace")
  File "C:\Osobni\rApp\rApp\acts.py", line 538, in getStringFromList
    for i in input[field]:
KeyError: 'Komunikace'
root - WARNING - s_barrieFree was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 285, in extractData
    s_barrieFree = dict_detailsTableOfOffer['Bezbariérový']
KeyError: 'Bezbariérový'
root - WARNING - s_parking was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 291, in extractData
    s_parking = dict_detailsTableOfOffer['Parkování']
KeyError: 'Parkování'
root - WARNING - s_terrace was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 297, in extractData
    s_terrace = dict_detailsTableOfOffer['Terasa']
KeyError: 'Terasa'
root - WARNING - s_cellar was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 303, in extractData
    s_cellar = dict_detailsTableOfOffer['Sklep']
KeyError: 'Sklep'
root - WARNING - s_garage was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 309, in extractData
    s_garage = dict_detailsTableOfOffer['Garáž']
KeyError: 'Garáž'
root - WARNING - s_equipped was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 315, in extractData
    s_equipped = dict_detailsTableOfOffer['Vybavení']
KeyError: 'Vybavení'
root - WARNING - s_transferToPersonalOwnership was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 321, in extractData
    s_transferToPersonalOwnership = dict_detailsTableOfOffer['Pøevod do OV']
KeyError: 'Pøevod do OV'
root - WARNING - s_yearOfApproval was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 327, in extractData
    s_yearOfApproval = dict_detailsTableOfOffer['Rok kolaudace']
KeyError: 'Rok kolaudace'
root - WARNING - culturalHeritageDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Kulturní památka'
root - WARNING - tramDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Tram'
root - WARNING - metroDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Metro'
root - WARNING - storeDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Obchod'
root - WARNING - naturalAttractionDistance was not grabbed.
Traceback (most recent call last):
  File "C:\Osobni\rApp\rApp\acts.py", line 367, in extractData
    dict_offerDetailsAttr[key] = dict_poi[value]
KeyError: 'Pøírodní zajímavost'
